### ISSUE TITLE
Switching to Prerelease doesn't work on OctoPi 1.0.0cam

### ISSUE THREAD

**Issue by b-morgan** [OctoPrint/OctoPrint-FileCheck#13]
On my OctoPi 0.18.0, OctoPrint 1.10.0rc3 system I checked Prerelease for OctoPrint-FileCheck plugin and it updated.

On my OctoPrint 1.10.0rc3 Python 3.9.2 OctoPi* 1.0.0cam (build 2023.07.20.144556) system, I check Prerelease and it just switches back to Stable.

**Comment by foosel** [comment]
Can you also share a system info bundle?

**Comment by b-morgan** [comment]
It may be too late... I just brought up a browser on the system with the issue and I got an announcement that there is an update for the File Check plugin. Here is the bundle before responding to the "Update Available" and I'll hold off on updating until I hear from you.

[octoprint-systeminfo-20240402054320.zip](https://github.com/OctoPrint/OctoPrint-FileCheck/files/14836000/octoprint-systeminfo-20240402054320.zip)

**Comment by foosel** [comment]
Ah, I seem to have misunderstood the issue.

Do I understand it correctly now that the **UI** switches itself back to Stable? As in, selecting the Prerelease release channel on the plugin just switches it right back to Stable? If so I think I'm seeing a reproduction here, though right now I can't make sense of it, and it also affects other plugins and even OctoPrint itself, so I'll have to dig into that in general.

In any case, I think you can go ahead with updating on your end.

**Comment by b-morgan** [comment]
Yes, the UI was switching itself back to "Stable".

**Comment by foosel** [comment]
I fear this is actually a bug with the settings optimizations in 1.10.0. I haven't yet fully understood why it works in some cases and in others doesn't, but it very much looks like a regression... Looks like I'll need to push out a 1.10.0rc4 after all :/

**Comment by foosel** [comment]
Yes, this is indeed due to an OctoPrint bug and now tracked in OctoPrint/OctoPrint#4983

For the record, it was a very specific corner case triggering a bug in the internal settings cache. My guess is the instance on which things worked for you had had the setting set at some point already, the other broken one didn't.
