### ISSUE TITLE
Fails update with: CSRF validation failed

### ISSUE THREAD

**Issue by alien8r** [OctoPrint/OctoPrint-FileCheck#14]
Octoprint notifies of available update "File Check Plugin: 2024.3.27"
Update fails with this message:
>The update could not be started. Is it already active? Please consult octoprint.log for details.
>CSRF validation failed

**Comment by foosel** [comment]
CSRF validation failed hints at the "update" request against the server failing due to CSRF validation, which had nothing to do with the plugin. Try reloading, logging out and back in.

If that doesn't help, create a system info bundle and share it here.

**Comment by foosel** [comment]
Closing this as it's not actionable, feel free to request a reopen if the above doesn't help and you can provide a bundle.
