### ISSUE TITLE
no access to Meta data 

### ISSUE THREAD

**Issue by fungreenfox** [OctoPrint/OctoPrint-FileCheck#15]
Found existing installation: OctoPrint-FileCheck 2021.2.23
 Uninstalling OctoPrint-FileCheck-2021.2.23:
Successfully uninstalled OctoPrint-FileCheck-2021.2.23
19,795 ! ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'METADATA'
19,795 ! Check the permissions.

**Comment by foosel** [comment]
Looks like you have some broken permissions on your instance, not an issue with the plugin but your environment.
